### ISSUE TITLE
Musepack in Audacious

### ISSUE THREAD

**Issue by IdolIcon** [ivan-hc/Database-of-pkg2appimaged-packages#1]
I can't listen mpc audio files with your Audacious appimage.
I'm not a developer so I don't know if it is possible:
May you include a codec with the application to be able to listen music in Musepack (mpc) format with your Audacious appimage, please?

By the way, thank you very much for your appimages, I appreciate your work a lot, specially your Chromium webbrowser appimage, that works like a charm. And VLC is great as well.

**Comment by ivan-hc** [comment]
hello, sorry if I answer only now. What plugins do you have on your client from the repositories? I've tried rebuilding the Appimage by including `ffmpeg`, `libmpc3` and `libmpcdec6`, I've also tried a different AppRun, but was unsuccessful. On the other hand, other formats are perfectly legible.

**Comment by IdolIcon** [comment]
I'm just a user, not a developer, so I don't know. I can tell you that I use Strawberry 0.9.3 appimage downloaded from here:

https://www.appimagehub.com/p/1288971

And it can play mpc files with no problem. I hope this can help you.

**Comment by IdolIcon** [comment]
**This new version plays .mpc files!!**

Thank you very much ivan-hc. I appreciate a lot your great work.
