### ISSUE TITLE
the path is error ,cannot play

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/Database-of-pkg2appimaged-packages#2]
![image](https://github.com/ivan-hc/Database-of-pkg2appimaged-packages/assets/87791643/526afcd0-5969-4149-bba1-983979f0fda3)

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/Database-of-pkg2appimaged-packages/commit/387014efe6d4a6fb65b18a0422e74244731709cd should solve the problem. With a custom AppRun, Audacious should be able to detect "libpango" on the system.
