### ISSUE TITLE
i download new version , but it show zsh: segmentation fault  ./Downloads/Audacious-x86_64.AppImage

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/Database-of-pkg2appimaged-packages#3]
![image](https://github.com/ivan-hc/Database-of-pkg2appimaged-packages/assets/87791643/30b0f30e-f385-4209-b8aa-52676105cc24)

cannot run Audacious to play

**Comment by ivan-hc** [comment]
strange, I've rebuilt it and works great for me (I use "`bash`")

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/Database-of-pkg2appimaged-packages/assets/88724353/c2dca19a-3a40-4239-814b-c1188c999030

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/KDE-utils-appimage/issues/3#issuecomment-1623943384
