### ISSUE TITLE
i3wm use simplescreenrecorder to record video , it show too long screen, not focus the windows

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/Database-of-pkg2appimaged-packages#4]
it show long screen , it just not realty

https://github.com/ivan-hc/Database-of-pkg2appimaged-packages/assets/87791643/f8044f4c-9bcf-4518-8942-aaa09c921126

**Comment by ivan-hc** [comment]
when you start SimpleScreenRecording you have a series of settings, from vido size to audio... just set them. It works well for me.

This has been recorded now with my resolution 1280x1024

https://github.com/ivan-hc/Database-of-pkg2appimaged-packages/assets/88724353/0bf06e18-9f81-4686-9545-185bf71bbc8c

**Comment by newyorkthink** [comment]
> when you start SimpleScreenRecording you have a series of settings, from vido size to audio... just set them. It works well for me.当您开始简单屏幕录制时，您有一系列设置，从视频大小到音频...只需设置它们。它对我来说效果很好。
> 
> This has been recorded now with my resolution 1280x1024这现在已经用我的分辨率 1280x1024 记录下来
> 
>  simplescreenrecorder-2023-07-14_15.11.55.mkv.mp4 
> 简单屏幕录像机-2023-07-14_15.11.55.mkv.mp4

is my Miss
