### ISSUE TITLE
AppImage file under the Audacious release heading is named Asunder-4.2-1-x86_64.AppImage

### ISSUE THREAD

**Issue by aluropod** [ivan-hc/Database-of-pkg2appimaged-packages#5]
The AppImage file under the Audacious release heading is named Asunder-4.2-1-x86_64.AppImage. Is this the correct AppImage for Audacious?  If it is, can I just rename it to Audacious.AppImage and it will still work as an AppImage? TIA for your hard work.

**Comment by ivan-hc** [comment]
Thank you for reporting, just fixed
