### ISSUE TITLE
SSR not running under Manjaro

### ISSUE THREAD

**Issue by ikabod** [ivan-hc/Database-of-pkg2appimaged-packages#6]
[user@manjaro AppImages]$ ./SimpleScreenRecorder.AppImage
execv error: No such file or directory
[user@manjaro AppImages]$ ./SimpleScreenRecorder.AppImage --no-sandbox
execv error: No such file or directory
[user@manjaro AppImages]$

If you need more information, please let me know.

**Comment by ivan-hc** [comment]
I have already seen that message.

Have you got AppImageLauncher or "appimaged" installed on your system?

**Comment by ikabod** [comment]
AppImageLauncher

**Comment by ivan-hc** [comment]
Remove it, reboot and retry

**Comment by ikabod** [comment]
Now it is starting, but not using the configuration under "SimpleScreenRecorder.AppImage.config" but under $HOME/.ssr

**Comment by ivan-hc** [comment]
> Now it is starting, but not using the configuration under "SimpleScreenRecorder.AppImage.config" but under $HOME/.ssr

I think that now its a free program, so you have a .ssr directory in the $HOME, like me. That conf file should be a AppImageLauncher-related file. I don't know how it handles appImages, I only know that it detects them in the system, and when another program (for example the terminal) is running it, you get the error you had in the first post.

AppImageLauncher is a good program, but it is too old (last stable was released in 2020, the last dev build in 2022) and my AppImages use the new runtime, that does not need libfuse2 installed. So they should be not compatible.

**Comment by ikabod** [comment]
"That conf file should be a AppImageLauncher-related file"

No, it is from AppImage:
https://docs.appimage.org/user-guide/portable-mode.html

Would be glad if you can fix this.

**Comment by ivan-hc** [comment]
Try to use a .home directory instead. Normalli SSR creates its configuration files in the $HOME

**Comment by ivan-hc** [comment]
.config is for programs that respect dotfiles specifisc, and SSR does not respect them

![Istantanea_2024-10-03_21-51-04 png](https://github.com/user-attachments/assets/d12dfb0b-a866-4f92-a646-d57b52cb7edb)

**Comment by ivan-hc** [comment]
![Istantanea_2024-10-03_21-54-06 png](https://github.com/user-attachments/assets/dcb6ac29-f3f5-452c-b248-e1db40ea437e)

**Comment by ivan-hc** [comment]
I can't record via video what I just did because I need just that subject (SSR) to record videos, so I sent screenshots

**Comment by ikabod** [comment]
Please read the documentation I provided by a link.

.config is not a file, it is a directory.

**Comment by ivan-hc** [comment]
```
ivan@debian:~$ ./*.AppImage --appimage-help
AppImage options:

  --appimage-extract [<pattern>]  Extract content from embedded filesystem image
                                  If pattern is passed, only extract matching files
  --appimage-help                 Print this help
  --appimage-mount                Mount embedded filesystem image and print
                                  mount point and wait for kill with Ctrl-C
  --appimage-offset               Print byte offset to start of embedded
                                  filesystem image
  --appimage-portable-home        Create a portable home folder to use as $HOME
  --appimage-portable-config      Create a portable config folder to use as
                                  $XDG_CONFIG_HOME
  --appimage-signature            Print digital signature embedded in AppImage
  --appimage-updateinfo[rmation]  Print update info embedded in AppImage
  --appimage-version              Print version of AppImage runtime

Portable home:

  If you would like the application contained inside this AppImage to store its
  data alongside this AppImage rather than in your home directory, then you can
  place a directory named

  /opt/avidemux/avidemux.home

  Or you can invoke this AppImage with the --appimage-portable-home option,
  which will create this directory for you. As long as the directory exists
  and is neither moved nor renamed, the application contained inside this
  AppImage to store its data in this directory rather than in your home
  directory

License:
  This executable contains code from
  * runtime, licensed under the terms of
    https://github.com/probonopd/static-tools/blob/master/LICENSE
  * musl libc, licensed under the terms of
    https://git.musl-libc.org/cgit/musl/tree/COPYRIGHT
  * libfuse, licensed under the terms of
    https://github.com/libfuse/libfuse/blob/master/LGPL2.txt
  * squashfuse, licensed under the terms of
    https://github.com/vasi/squashfuse/blob/master/LICENSE
  * libzstd, licensed under the terms of
    https://github.com/facebook/zstd/blob/dev/LICENSE
  * zlib, licensed under the terms of
    https://zlib.net/zlib_license.html
Please see https://github.com/probonopd/static-tools/
for information on how to obtain and build the source code
```

**Comment by ivan-hc** [comment]
I have been using SSR since GTK-RecordMyDesktop was discontinued, I think it's been 10 years now. I know very well that SSR creates a directory in $HOME .ssr. The only way to avoid creating it is to use a .home directory, that's where the LOGs are stored more than anything else. The configurations in ~/.config, so you need a .config directory.

You can create them respectively using the following options:
```
./*.AppImage --appimage-portable-home
./*.AppImage --appimage-portable-config
```

I showed you screenshots of how the two directories work.

**Comment by ivan-hc** [comment]
I have been building AppImages for years, I am aware of the documentation.

**Comment by ivan-hc** [comment]
I close, the basic problem was the presence of AppImageLauncher in the system.

The rest of the discussion is part of a problem that does not concern the AppImage, but is a "tutorial" on how the options `--appimage-portable-home` and `--appimage-portable-config` work and how and where SSR (present on AUR, in Arch Linux, but still present in the main repos of Debian) saves its dotfiles... which is a problem of the application itself, not of the AppImage (and nothing can be done, as long as SSR is no longer developed for years, that's why it is in the AUR and no longer in the main repos of Arch Linux). So this is off topic.
